CREATE TABLE client (
	USERID VARCHAR(20) NOT NULL,
	INDIP VARCHAR(45) NOT NULL,
	PORTA INT NOT NULL,
	TIPOCONN VARCHAR(45) NOT NULL,
	PRIMARY KEY (USERID)
);

CREATE TABLE ownership (
	FILE INT NOT NULL,
	UTENTE VARCHAR(20) NOT NULL,
	PRIMARY KEY (FILE,UTENTE)
);

CREATE TABLE disk (
	NOME VARCHAR(20) NOT NULL,
	DIMENSIONE INT NOT NULL,
	USERID VARCHAR(20) NOT NULL,
	CARTELLAROOT INT NOT NULL,
	PRIMARY KEY (NOME)
);

CREATE TABLE user (
	USERID VARCHAR(20) NOT NULL,
	NOME VARCHAR(45) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(45) NOT NULL,
	admin BIT DEFAULT 0 NOT NULL,
	PRIMARY KEY (USERID)
);

CREATE TABLE download (
	TICKET INT NOT NULL,
	FILE INT NOT NULL,
	UTENTE VARCHAR(20) NOT NULL,
	TIMESTAMP DATETIME NOT NULL,
	PRIMARY KEY (TICKET)
);

CREATE TABLE file (
	CODICE INT NOT NULL,
	NOME VARCHAR(45) NOT NULL,
	DIMENSIONE INT NOT NULL,
	CARTELLA INT NOT NULL,
	AUTORE VARCHAR(45) NOT NULL,
	UTENTEINS VARCHAR(45) NOT NULL,
	PRIMARY KEY (CODICE)
);

CREATE TABLE extension (
	allow BIT NOT NULL,
	name VARCHAR(20) NOT NULL,
	PRIMARY KEY (name)
);

CREATE TABLE folder (
	CODICE INT NOT NULL,
	NOME VARCHAR(20) NOT NULL,
	DIMENSIONE INT NOT NULL,
	parent INT,
	prova BIT DEFAULT 1 NOT NULL,
	PRIMARY KEY (CODICE)
);

CREATE INDEX FK_disco_2 ON disk (USERID ASC);

CREATE UNIQUE INDEX Index_2 ON file (CARTELLA ASC, NOME ASC);

CREATE INDEX FK_download_1 ON download (FILE ASC);

CREATE INDEX FK_file_2 ON file (UTENTEINS ASC);

CREATE INDEX FK_download_2 ON download (UTENTE ASC);

CREATE UNIQUE INDEX Index_2 ON client (INDIP ASC, PORTA ASC);

CREATE INDEX FK_appartenenza_2 ON ownership (UTENTE ASC);

CREATE INDEX FK_disco_1 ON disk (CARTELLAROOT ASC);

ALTER TABLE extension ADD PRIMARY KEY (name);

ALTER TABLE folder ADD PRIMARY KEY (CODICE);

ALTER TABLE file ADD PRIMARY KEY (CODICE);

ALTER TABLE user ADD PRIMARY KEY (USERID);

ALTER TABLE file ADD CONSTRAINT FK_file_1 FOREIGN KEY (CARTELLA)
	REFERENCES folder (CODICE);

ALTER TABLE client ADD CONSTRAINT FK_user_1 FOREIGN KEY (USERID)
	REFERENCES user (USERID);

ALTER TABLE ownership ADD CONSTRAINT FK_appartenenza_2 FOREIGN KEY (UTENTE)
	REFERENCES user (USERID);

ALTER TABLE file ADD CONSTRAINT FK_file_2 FOREIGN KEY (UTENTEINS)
	REFERENCES user (USERID);

ALTER TABLE download ADD CONSTRAINT FK_download_1 FOREIGN KEY (FILE)
	REFERENCES file (CODICE);

ALTER TABLE disk ADD CONSTRAINT FK_disco_1 FOREIGN KEY (CARTELLAROOT)
	REFERENCES folder (CODICE);

ALTER TABLE ownership ADD CONSTRAINT FK_appartenenza_1 FOREIGN KEY (FILE)
	REFERENCES file (CODICE);

ALTER TABLE download ADD CONSTRAINT FK_download_2 FOREIGN KEY (UTENTE)
	REFERENCES user (USERID);

ALTER TABLE disk ADD CONSTRAINT FK_disco_2 FOREIGN KEY (USERID)
	REFERENCES user (USERID);

